// Generated by CoffeeScript 1.7.1
var filterLongWords, grades, pluralizer, reverse,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

reverse = function(name) {
  reverse = name.split("").reverse().join("");
  return reverse;
};

console.log(reverse("Sam"));

filterLongWords = function(word, count) {
  var element, result, _i, _len;
  result = [];
  for (_i = 0, _len = word.length; _i < _len; _i++) {
    element = word[_i];
    if (element.length > count) {
      result.push(element);
    }
  }
  return result;
};

console.log(filterLongWords(["Sam", "John", "Alexander", "Escondido", "Boobella buttocks"], 4));

grades = function(value) {
  switch (false) {
    case __indexOf.call([90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], value) < 0:
      return "A";
    case __indexOf.call([80, 81, 82, 83, 84, 85, 86, 87, 88, 89], value) < 0:
      return "B";
    case __indexOf.call([70, 71, 72, 73, 74, 75, 76, 77, 78, 79], value) < 0:
      return "C";
    case __indexOf.call([60, 61, 62, 63, 64, 65, 66, 67, 68, 69], value) < 0:
      return "D";
    case __indexOf.call([50, 51, 52, 53, 54, 55, 56, 57, 58, 59], value) < 0:
      return "F";
  }
};

console.log(grades(55));

pluralizer = function(noun, number) {
  var result;
  if (number > 1) {
    result = "" + number + " " + noun;
    if (number >= 2) {
      result += "s";
    }
    return result;
  }
};

console.log(pluralizer("cat", 5));

console.log(pluralizer("pizza", 3));

console.log(pluralizer("girl", 1));
